[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.0.1"
version_files = ["graph-demo/__init__.py"]
update_changelog_on_bump = true
major_version_zero = true

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.ruff.lint]
preview = true
select = ["E", "F", "W", "I"]
ignore = []
